USE [master]
GO
/****** Object:  Database [XBankDB]    Script Date: 28.02.2019 21:02:07 ******/
CREATE DATABASE [XBankDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'XBankDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\XBankDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'XBankDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\XBankDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [XBankDB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XBankDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [XBankDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [XBankDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [XBankDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [XBankDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [XBankDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [XBankDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [XBankDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [XBankDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [XBankDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [XBankDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [XBankDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [XBankDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [XBankDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [XBankDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [XBankDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [XBankDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [XBankDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [XBankDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [XBankDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [XBankDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [XBankDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [XBankDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [XBankDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [XBankDB] SET RECOVERY FULL 
GO
ALTER DATABASE [XBankDB] SET  MULTI_USER 
GO
ALTER DATABASE [XBankDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [XBankDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [XBankDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [XBankDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
USE [XBankDB]
GO
/****** Object:  Table [dbo].[tbl_Customers]    Script Date: 28.02.2019 21:02:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](50) NOT NULL,
	[CustomerSurname] [nvarchar](50) NOT NULL,
	[CustomerPasskey] [nvarchar](50) NOT NULL,
	[Balance] [money] NOT NULL,
	[BalanceType] [tinyint] NOT NULL,
	[isActive] [bit] NOT NULL,
 CONSTRAINT [PK_tbl_Customers] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[tbl_Transactions]    Script Date: 28.02.2019 21:02:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Transactions](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[TransactionAmount] [money] NOT NULL,
	[TransactorAccountNumber] [int] NOT NULL,
	[RecieverAccountNumber] [int] NULL,
	[TransactionDate] [datetime] NOT NULL,
	[isSuccess] [bit] NOT NULL,
 CONSTRAINT [PK_tbl_Transactions] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[tbl_Transactions]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Transactions_tbl_Customers] FOREIGN KEY([TransactorAccountNumber])
REFERENCES [dbo].[tbl_Customers] ([CustomerID])
GO
ALTER TABLE [dbo].[tbl_Transactions] CHECK CONSTRAINT [FK_tbl_Transactions_tbl_Customers]
GO
USE [master]
GO
ALTER DATABASE [XBankDB] SET  READ_WRITE 
GO
